/**
 * Contract Template Identifier — LOCKED V3.0 (approved 2026-03-18)
 * Used by field sales and prepaid contract generators.
 */

export const ACTIVE_CONTRACT_TEMPLATE = {
  id: "contract-v3-locked-2026-03-18",
  version: "V3.0",
  updatedAt: "2026-03-18T00:00:00.000Z",
} as const;

export const getContractEngineFooterLine = (params: {
  contractId?: string | null;
  templateVersion?: string | null;
}) => {
  const contractId = params.contractId || "UNKNOWN";
  const templateVersion = params.templateVersion || ACTIVE_CONTRACT_TEMPLATE.version;
  return `Generated by Nivra – Contract Engine – Template ${templateVersion} – ContractID: ${contractId}`;
};
