export const ACTIVE_CONTRACT_TEMPLATE = {
  id: "contract_template_v2026_01_02_prepaid",
  version: "v2026.01.02-Prepaid-01",
  updatedAt: "2026-01-02T12:00:00.000Z",
} as const;

export const getContractEngineFooterLine = (params: {
  contractId?: string | null;
  templateVersion?: string | null;
}) => {
  const contractId = params.contractId || "UNKNOWN";
  const templateVersion = params.templateVersion || ACTIVE_CONTRACT_TEMPLATE.version;

  // Must match requested wording (proof of template)
  return `Generated by Nivra – Contract Engine – Template ${templateVersion} – ContractID: ${contractId}`;
};
