/**
 * MarketingEmailCampaignsPage — Phase 1 rebuild.
 *
 * Tabbed Marketing Hub email center using existing backend:
 *   - email_campaigns / email_templates  (campaign + template storage)
 *   - email_unsubscribes                 (suppression list, auto-excluded by edge function)
 *   - send-marketing-email edge function (now supports preview_count + city/language filters)
 *
 * Anti-spam: every email goes through the corporate template which already
 * includes the unsubscribe link, plain-text alt content is generated by the
 * shared ResendProxy, and the existing email queue handles throttling.
 *
 * Phase 2 (next turn) will add the public /unsubscribe page, open/click
 * tracking edge functions, and the timeline charts.
 */
import { useEffect, useMemo, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Badge } from "@/components/ui/badge";
import {
  Send, Loader2, Mail, Eye, MousePointer, AlertTriangle, Calendar, Users,
  FileText, Ban, BarChart3, Sparkles, Plus, RotateCcw, TestTube2, Save,
} from "lucide-react";
import { toast } from "sonner";
import { format, subDays, startOfDay } from "date-fns";
import { fr as frLocale } from "date-fns/locale";
import { ResponsiveContainer, LineChart, Line, XAxis, YAxis, Tooltip, CartesianGrid } from "recharts";
import { MKPage, MKCard, MKCardHeader, MKStat } from "./_marketing-ui";
import MarketingContactsPanel from "./MarketingContactsPanel";

// ─── Types ─────────────────────────────────────────────────────────────────

interface Campaign {
  id: string;
  name: string;
  campaign_number: string | null;
  subject_override: string | null;
  status: string;
  total_recipients: number;
  total_sent: number;
  total_delivered: number;
  total_opened: number;
  total_clicked: number;
  total_bounced: number;
  total_unsubscribed: number;
  scheduled_at: string | null;
  started_at: string | null;
  completed_at: string | null;
  created_at: string;
  segment_filters: Record<string, any> | null;
}

interface Unsubscribe {
  id: string;
  email: string;
  reason: string | null;
  unsubscribed_at: string;
  source: string | null;
  is_active: boolean;
}

interface Template {
  id: string;
  name: string;
  subject: string;
  category: string;
  created_at: string;
}

// ─── Brand corporate template (preserved from previous version) ────────────

const buildCorporateHtml = (subject: string, bodyFr: string, bodyEn?: string) => {
  const blockFr = `<div lang="fr">${bodyFr.replace(/\n/g, "<br/>")}</div>`;
  const blockEn = bodyEn
    ? `<hr style="margin:24px 0;border:none;border-top:1px solid #e5e7eb;"/><div lang="en">${bodyEn.replace(/\n/g, "<br/>")}</div>`
    : "";
  return `
<table width="100%" cellpadding="0" cellspacing="0" style="background:#f4f6fa;padding:24px 0;font-family:Arial,sans-serif;">
  <tr><td align="center">
    <table width="600" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:8px;overflow:hidden;">
      <tr><td style="background:#0066CC;padding:24px;text-align:center;color:#ffffff;font-size:20px;font-weight:bold;">Nivra Télécom</td></tr>
      <tr><td style="padding:32px;color:#1a1a1a;font-size:15px;line-height:1.6;">
        <div style="font-size:18px;font-weight:600;color:#0066CC;margin-bottom:16px;">${subject}</div>
        ${blockFr}${blockEn}
      </td></tr>
      <tr><td style="background:#f4f6fa;padding:16px;text-align:center;color:#6b7280;font-size:12px;">
        © ${new Date().getFullYear()} Nivra Télécom · Vous recevez cet email car vous êtes client Nivra.<br/>
        <a href="{{unsubscribe_link}}" style="color:#0066CC;text-decoration:underline;">Se désabonner</a> ·
        <a href="mailto:support@nivra-telecom.ca" style="color:#0066CC;text-decoration:underline;">Nous contacter</a>
      </td></tr>
    </table>
  </td></tr>
</table>`.trim();
};

// ─── Pre-built templates library ───────────────────────────────────────────

const PREBUILT_TEMPLATES = [
  {
    key: "welcome",
    title: "Bienvenue nouveau client",
    subjectFr: "Bienvenue chez Nivra, {{client_name}} !",
    subjectEn: "Welcome to Nivra, {{client_name}}!",
    bodyFr: "Bonjour {{client_name}},\n\nMerci d'avoir choisi Nivra Télécom. Votre service est maintenant actif et nous sommes ravis de vous compter parmi nos clients.\n\nPour toute question, écrivez-nous à support@nivra-telecom.ca.\n\nL'équipe Nivra",
    bodyEn: "Hello {{client_name}},\n\nThank you for choosing Nivra Telecom. Your service is now active and we are delighted to have you with us.\n\nFor any question, write us at support@nivra-telecom.ca.\n\nThe Nivra team",
  },
  {
    key: "first_month_free",
    title: "Offre — Premier mois gratuit",
    subjectFr: "🎁 Votre premier mois est offert avec NIVRA2026",
    subjectEn: "🎁 Your first month is on us with NIVRA2026",
    bodyFr: "Bonjour {{client_name}},\n\nProfitez du code NIVRA2026 pour obtenir votre premier mois gratuit sur tout nouveau service.\n\nValide une fois par client. Visitez nivra-telecom.ca pour en profiter.",
    bodyEn: "Hello {{client_name}},\n\nUse code NIVRA2026 and get your first month free on any new service.\n\nOne use per client. Visit nivra-telecom.ca to redeem.",
  },
  {
    key: "renewal_reminder",
    title: "Rappel de renouvellement",
    subjectFr: "Votre renouvellement Nivra approche",
    subjectEn: "Your Nivra renewal is coming up",
    bodyFr: "Bonjour {{client_name}},\n\nVotre prochaine facture sera générée prochainement. Aucune action requise — votre service continuera sans interruption.\n\nMerci de votre confiance.",
    bodyEn: "Hello {{client_name}},\n\nYour next invoice will be generated shortly. No action required — your service will continue uninterrupted.\n\nThank you for your trust.",
  },
  {
    key: "new_plan",
    title: "Annonce nouveau forfait",
    subjectFr: "Découvrez notre nouveau forfait Nivra",
    subjectEn: "Discover our new Nivra plan",
    bodyFr: "Bonjour {{client_name}},\n\nNous lançons un nouveau forfait pensé pour vous. Découvrez les détails sur nivra-telecom.ca.\n\nL'équipe Nivra",
    bodyEn: "Hello {{client_name}},\n\nWe are launching a new plan designed for you. Discover the details at nivra-telecom.ca.\n\nThe Nivra team",
  },
  {
    key: "satisfaction",
    title: "Sondage satisfaction",
    subjectFr: "Comment évaluez-vous votre expérience Nivra ?",
    subjectEn: "How would you rate your Nivra experience?",
    bodyFr: "Bonjour {{client_name}},\n\nVotre avis compte. Prenez 30 secondes pour nous dire ce que vous pensez de votre service.\n\nRépondez simplement à cet email — nous lisons chaque message.",
    bodyEn: "Hello {{client_name}},\n\nYour feedback matters. Take 30 seconds to tell us what you think of your service.\n\nJust reply to this email — we read every message.",
  },
] as const;

const PERSONALIZATION_TOKENS = [
  { token: "{{client_name}}", label: "Prénom + Nom" },
  { token: "{{client_email}}", label: "Email" },
  { token: "{{prenom}}", label: "Prénom (alias)" },
  { token: "{{ville}}", label: "Ville" },
  { token: "{{forfait}}", label: "Forfait actif" },
  { token: "{{prix}}", label: "Prix mensuel" },
];

// ─── Optimal send time hint ────────────────────────────────────────────────

function nextOptimalSendTime(): Date {
  // Tuesday-Thursday 10:00–14:00 (America/Toronto). Cheap heuristic.
  const d = new Date();
  d.setMinutes(0, 0, 0);
  for (let i = 0; i < 14; i++) {
    const cand = new Date(d.getTime() + i * 24 * 60 * 60 * 1000);
    const day = cand.getDay(); // 0 = Sun
    if (day >= 2 && day <= 4) {
      cand.setHours(10, 0, 0, 0);
      if (cand.getTime() > Date.now()) return cand;
    }
  }
  return new Date(Date.now() + 24 * 60 * 60 * 1000);
}

// ═══════════════════════════════════════════════════════════════════════════
// Page
// ═══════════════════════════════════════════════════════════════════════════

const MarketingEmailCampaignsPage = () => {
  const [tab, setTab] = useState("campaigns");

  // Lists
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [unsubs, setUnsubs] = useState<Unsubscribe[]>([]);
  const [templates, setTemplates] = useState<Template[]>([]);
  const [loading, setLoading] = useState(true);
  const [opensTimeline, setOpensTimeline] = useState<{ date: string; opens: number; clicks: number }[]>([]);

  // Builder state
  const [name, setName] = useState("");
  const [audience, setAudience] = useState<"all" | "active" | "cancelled">("all");
  const [language, setLanguage] = useState<"both" | "fr" | "en">("both");
  const [city, setCity] = useState("");
  const [lang, setLang] = useState<"fr" | "en">("fr");
  const [subjectFr, setSubjectFr] = useState("");
  const [subjectEn, setSubjectEn] = useState("");
  const [bodyFr, setBodyFr] = useState("");
  const [bodyEn, setBodyEn] = useState("");
  const [scheduleNow, setScheduleNow] = useState<"now" | "later">("now");
  const [scheduledAt, setScheduledAt] = useState("");
  const [recipientCount, setRecipientCount] = useState<number | null>(null);
  const [previewing, setPreviewing] = useState(false);
  const [creating, setCreating] = useState(false);
  const [savingDraft, setSavingDraft] = useState(false);
  const [sendingTest, setSendingTest] = useState(false);
  const [testEmail, setTestEmail] = useState("support@nivra-telecom.ca");

  // ── Data loaders ─────────────────────────────────────────────────────────

  const loadCampaigns = async () => {
    const { data } = await supabase
      .from("email_campaigns")
      .select("*")
      .order("created_at", { ascending: false })
      .limit(100);
    setCampaigns((data ?? []) as Campaign[]);
  };

  const loadUnsubs = async () => {
    const { data } = await supabase
      .from("email_unsubscribes")
      .select("id, email, reason, unsubscribed_at, source, is_active")
      .order("unsubscribed_at", { ascending: false })
      .limit(200);
    setUnsubs((data ?? []) as Unsubscribe[]);
  };

  const loadTemplates = async () => {
    const { data } = await supabase
      .from("email_templates")
      .select("id, name, subject, category, created_at")
      .eq("category", "marketing")
      .order("created_at", { ascending: false })
      .limit(50);
    setTemplates((data ?? []) as Template[]);
  };

  const loadOpensTimeline = async () => {
    const since = subDays(new Date(), 30).toISOString();
    const [opensRes, clicksRes] = await Promise.all([
      supabase.from("email_sends").select("opened_at").gte("opened_at", since).not("opened_at", "is", null).limit(5000),
      supabase.from("email_sends").select("clicked_at").gte("clicked_at", since).not("clicked_at", "is", null).limit(5000),
    ]);
    const buckets = new Map<string, { opens: number; clicks: number }>();
    for (let i = 29; i >= 0; i--) {
      const key = format(startOfDay(subDays(new Date(), i)), "yyyy-MM-dd");
      buckets.set(key, { opens: 0, clicks: 0 });
    }
    (opensRes.data ?? []).forEach((r: any) => {
      const k = format(startOfDay(new Date(r.opened_at)), "yyyy-MM-dd");
      const b = buckets.get(k); if (b) b.opens += 1;
    });
    (clicksRes.data ?? []).forEach((r: any) => {
      const k = format(startOfDay(new Date(r.clicked_at)), "yyyy-MM-dd");
      const b = buckets.get(k); if (b) b.clicks += 1;
    });
    setOpensTimeline(Array.from(buckets.entries()).map(([date, v]) => ({
      date: format(new Date(date), "d MMM", { locale: frLocale }),
      opens: v.opens,
      clicks: v.clicks,
    })));
  };

  useEffect(() => {
    (async () => {
      setLoading(true);
      await Promise.all([loadCampaigns(), loadUnsubs(), loadTemplates(), loadOpensTimeline()]);
      setLoading(false);
    })();
    const ch = supabase
      .channel("marketing-email-hub")
      .on("postgres_changes", { event: "*", schema: "public", table: "email_campaigns" }, loadCampaigns)
      .on("postgres_changes", { event: "*", schema: "public", table: "email_unsubscribes" }, loadUnsubs)
      .on("postgres_changes", { event: "*", schema: "public", table: "email_sends" }, loadOpensTimeline)
      .subscribe();
    return () => { supabase.removeChannel(ch); };
  }, []);

  // ── Builder helpers ──────────────────────────────────────────────────────

  const segmentFilters = useMemo(() => {
    const f: Record<string, any> = {};
    if (audience === "active") f.status = ["active"];
    else if (audience === "cancelled") f.status = ["cancelled"];
    if (language !== "both") f.language = language;
    if (city.trim()) f.city = city.trim();
    return f;
  }, [audience, language, city]);

  const resetBuilder = () => {
    setName(""); setAudience("all"); setLanguage("both"); setCity("");
    setSubjectFr(""); setSubjectEn(""); setBodyFr(""); setBodyEn("");
    setScheduleNow("now"); setScheduledAt(""); setRecipientCount(null);
  };

  const insertToken = (token: string) => {
    if (lang === "fr") setBodyFr((b) => b + (b.endsWith(" ") || b === "" ? "" : " ") + token);
    else setBodyEn((b) => b + (b.endsWith(" ") || b === "" ? "" : " ") + token);
  };

  const previewRecipients = async () => {
    setPreviewing(true);
    try {
      const { data, error } = await supabase.functions.invoke("send-marketing-email", {
        body: { preview_count: true, segment_filters: segmentFilters },
      });
      if (error) throw error;
      setRecipientCount((data as any)?.total_recipients ?? 0);
    } catch (e: any) {
      toast.error(e.message || "Erreur lors du calcul");
    } finally {
      setPreviewing(false);
    }
  };

  // Re-compute on segment change (debounced via dep array)
  useEffect(() => {
    setRecipientCount(null);
  }, [audience, language, city]);

  const applyPrebuilt = (t: typeof PREBUILT_TEMPLATES[number]) => {
    setName(t.title);
    setSubjectFr(t.subjectFr); setSubjectEn(t.subjectEn);
    setBodyFr(t.bodyFr); setBodyEn(t.bodyEn);
    setTab("new");
    toast.success(`Template "${t.title}" chargé`);
  };

  // ── Save / send actions ──────────────────────────────────────────────────

  const ensureTemplate = async (): Promise<{ id: string }> => {
    const html = buildCorporateHtml(subjectFr, bodyFr, bodyEn);
    const { data: tpl, error } = await supabase
      .from("email_templates")
      .insert({
        name: `marketing-${Date.now()}-${name.slice(0, 24).replace(/\s+/g, "-")}`,
        subject: subjectFr,
        html_content: html,
        variables: ["client_name", "client_email", "unsubscribe_link"],
        category: "marketing",
      })
      .select("id").single();
    if (error || !tpl) throw error || new Error("Template creation failed");
    return tpl;
  };

  const handleSaveDraft = async () => {
    if (!name.trim() || !subjectFr.trim() || !bodyFr.trim()) {
      toast.error("Nom, sujet (FR) et corps (FR) requis"); return;
    }
    setSavingDraft(true);
    try {
      const tpl = await ensureTemplate();
      const { error } = await supabase.from("email_campaigns").insert({
        name, template_id: tpl.id, subject_override: subjectFr,
        type: "manual", status: "draft", segment_filters: segmentFilters,
      });
      if (error) throw error;
      toast.success("Brouillon enregistré");
      resetBuilder();
      loadCampaigns(); loadTemplates();
      setTab("campaigns");
    } catch (e: any) {
      toast.error(e.message || "Erreur");
    } finally {
      setSavingDraft(false);
    }
  };

  const handleSendTest = async () => {
    if (!testEmail.trim() || !subjectFr.trim() || !bodyFr.trim()) {
      toast.error("Email de test, sujet et corps FR requis"); return;
    }
    setSendingTest(true);
    try {
      // Create a one-shot test template (not linked to a campaign)
      const tpl = await ensureTemplate();
      const { error } = await supabase.functions.invoke("send-marketing-email", {
        body: { template_id: tpl.id, test_email: testEmail.trim(), subject_override: `[TEST] ${subjectFr}` },
      });
      if (error) throw error;
      toast.success(`Email test envoyé à ${testEmail}`);
    } catch (e: any) {
      toast.error(e.message || "Erreur");
    } finally {
      setSendingTest(false);
    }
  };

  const handleCreate = async () => {
    if (!name.trim() || !subjectFr.trim() || !bodyFr.trim()) {
      toast.error("Nom, sujet (FR) et corps (FR) requis"); return;
    }
    if (scheduleNow === "later" && !scheduledAt) {
      toast.error("Sélectionnez une date de planification"); return;
    }
    setCreating(true);
    try {
      const tpl = await ensureTemplate();
      const isScheduled = scheduleNow === "later" && scheduledAt;
      const { data: campaign, error } = await supabase
        .from("email_campaigns")
        .insert({
          name, template_id: tpl.id, subject_override: subjectFr,
          type: "manual", status: isScheduled ? "scheduled" : "draft",
          segment_filters: segmentFilters,
          scheduled_at: isScheduled ? new Date(scheduledAt).toISOString() : null,
        })
        .select("id").single();
      if (error || !campaign) throw error || new Error("Campaign creation failed");

      if (!isScheduled) {
        const { error: sendErr } = await supabase.functions.invoke("send-marketing-email", {
          body: { campaign_id: campaign.id },
        });
        if (sendErr) throw sendErr;
        toast.success("Campagne envoyée");
      } else {
        toast.success("Campagne planifiée");
      }
      resetBuilder();
      loadCampaigns(); loadTemplates();
      setTab("campaigns");
    } catch (e: any) {
      toast.error(e.message || "Erreur");
    } finally {
      setCreating(false);
    }
  };

  const handleResubscribe = async (id: string, email: string) => {
    const { error } = await supabase
      .from("email_unsubscribes")
      .update({ is_active: false, resubscribed_at: new Date().toISOString() })
      .eq("id", id);
    if (error) { toast.error(error.message); return; }
    toast.success(`${email} ré-abonné`);
    loadUnsubs();
  };

  const handleSendToSelected = async ({
    client_ids, crm_contact_ids,
  }: { client_ids: string[]; crm_contact_ids: string[] }) => {
    if (!subjectFr.trim() || !bodyFr.trim()) {
      toast.error("Sujet et corps FR requis — remplissez l'onglet Nouveau"); return;
    }
    try {
      const tpl = await ensureTemplate();
      const total = client_ids.length + crm_contact_ids.length;
      // Send in two shots — the edge function targets one source per invocation.
      if (client_ids.length > 0) {
        const { error } = await supabase.functions.invoke("send-marketing-email", {
          body: { template_id: tpl.id, client_ids, subject_override: subjectFr },
        });
        if (error) throw error;
      }
      if (crm_contact_ids.length > 0) {
        const { error } = await supabase.functions.invoke("send-marketing-email", {
          body: { template_id: tpl.id, crm_contact_ids, subject_override: subjectFr },
        });
        if (error) throw error;
      }
      toast.success(`Envoi lancé vers ${total} contacts`);
    } catch (e: any) {
      toast.error(e.message || "Erreur lors de l'envoi");
    }
  };

  // ── Global stats ─────────────────────────────────────────────────────────

  const stats = useMemo(() => {
    const totalSent = campaigns.reduce((s, c) => s + (c.total_sent || 0), 0);
    const totalOpened = campaigns.reduce((s, c) => s + (c.total_opened || 0), 0);
    const totalClicked = campaigns.reduce((s, c) => s + (c.total_clicked || 0), 0);
    const totalBounced = campaigns.reduce((s, c) => s + (c.total_bounced || 0), 0);
    const activeUnsubs = unsubs.filter((u) => u.is_active).length;
    const openRate = totalSent ? Math.round((totalOpened / totalSent) * 100) : 0;
    const clickRate = totalSent ? Math.round((totalClicked / totalSent) * 100) : 0;
    return { totalSent, totalOpened, totalClicked, totalBounced, activeUnsubs, openRate, clickRate };
  }, [campaigns, unsubs]);

  const optimalHint = useMemo(() => {
    const d = nextOptimalSendTime();
    return format(d, "EEEE d MMMM 'à' HH:mm", { locale: frLocale });
  }, []);

  // ═══════════════════════════════════════════════════════════════════════
  // Render
  // ═══════════════════════════════════════════════════════════════════════

  return (
    <MKPage
      title="Campagnes Email"
      subtitle="Marketing — design corporate · anti-spam intégré"
      actions={
        <Button
          onClick={() => setTab("new")}
          className="rounded-[10px] text-white border-0 h-9 font-semibold"
          style={{ background: "#7C3AED" }}
        >
          <Plus className="h-4 w-4 mr-1.5" /> Nouvelle campagne
        </Button>
      }
    >
      <Tabs value={tab} onValueChange={setTab}>
        <TabsList className="bg-[#0D0D1A] border border-[#1E1E2E] rounded-[10px] p-1 h-auto flex-wrap">
          <TabTrigger value="campaigns" icon={Mail}>Campagnes</TabTrigger>
          <TabTrigger value="new" icon={Plus}>Nouveau</TabTrigger>
          <TabTrigger value="contacts" icon={Users}>Contacts</TabTrigger>
          <TabTrigger value="templates" icon={FileText}>Templates</TabTrigger>
          <TabTrigger value="unsubs" icon={Ban}>Désabonnements</TabTrigger>
          <TabTrigger value="stats" icon={BarChart3}>Statistiques</TabTrigger>
        </TabsList>

        {/* ─── Campagnes ─────────────────────────────────────────────── */}
        <TabsContent value="campaigns" className="mt-4">
          <MKCard>
            <MKCardHeader title={`Historique · ${campaigns.length}`} />
            <div className="p-2">
              {loading ? (
                <Loading />
              ) : campaigns.length === 0 ? (
                <Empty icon={Mail} text="Aucune campagne" />
              ) : (
                <div className="space-y-2">
                  {campaigns.map((c) => <CampaignRow key={c.id} c={c} />)}
                </div>
              )}
            </div>
          </MKCard>
        </TabsContent>

        {/* ─── Builder ───────────────────────────────────────────────── */}
        <TabsContent value="new" className="mt-4">
          <div className="grid lg:grid-cols-[1fr_1fr] gap-4">
            {/* Composer */}
            <MKCard>
              <MKCardHeader title="Nouvelle campagne" />
              <div className="p-5 space-y-4">
                <Field label="Nom de la campagne">
                  <Input
                    value={name} onChange={(e) => setName(e.target.value)}
                    placeholder="Ex: Promo printemps 2026"
                    className="bg-[#1E1E2E] border-[#1E1E2E] text-white placeholder:text-[#888] rounded-[10px]"
                  />
                </Field>

                {/* Segmentation */}
                <div className="rounded-[10px] border border-[#1E1E2E] bg-[#0a0a14] p-3 space-y-3">
                  <div className="text-[10px] uppercase tracking-[2px] text-[#888]">Audience</div>
                  <div className="grid grid-cols-3 gap-2">
                    <SmallSelect
                      label="Statut" value={audience} onChange={(v) => setAudience(v as any)}
                      options={[
                        { v: "all", l: "Tous" },
                        { v: "active", l: "Actifs" },
                        { v: "cancelled", l: "Annulés" },
                      ]}
                    />
                    <SmallSelect
                      label="Langue" value={language} onChange={(v) => setLanguage(v as any)}
                      options={[
                        { v: "both", l: "Les deux" },
                        { v: "fr", l: "Français" },
                        { v: "en", l: "English" },
                      ]}
                    />
                    <div>
                      <div className="text-[10px] uppercase tracking-[2px] text-[#888] mb-1">Ville</div>
                      <Input
                        value={city} onChange={(e) => setCity(e.target.value)}
                        placeholder="Toutes"
                        className="bg-[#1E1E2E] border-[#1E1E2E] text-white placeholder:text-[#666] rounded-[10px] h-9 text-sm"
                      />
                    </div>
                  </div>
                  <div className="flex items-center justify-between pt-1">
                    <Button
                      onClick={previewRecipients} disabled={previewing}
                      variant="ghost" size="sm"
                      className="h-8 text-[#7C3AED] hover:text-[#9d6bff] hover:bg-[#7C3AED15]"
                    >
                      {previewing ? <Loader2 className="h-3.5 w-3.5 animate-spin mr-1.5" /> : <Users className="h-3.5 w-3.5 mr-1.5" />}
                      Calculer destinataires
                    </Button>
                    {recipientCount !== null && (
                      <Badge className="bg-[#10B98122] text-[#10B981] border-0 font-mono">
                        {recipientCount} destinataires
                      </Badge>
                    )}
                  </div>
                  <p className="text-[10px] text-[#666]">
                    Les désabonnés sont automatiquement exclus.
                  </p>
                </div>

                {/* Bilingual content */}
                <Tabs value={lang} onValueChange={(v) => setLang(v as "fr" | "en")}>
                  <TabsList className="w-full bg-[#1E1E2E] rounded-[10px] h-9">
                    <TabsTrigger value="fr" className="flex-1 data-[state=active]:bg-[#7C3AED] data-[state=active]:text-white text-[#888] rounded-md">🇫🇷 Français</TabsTrigger>
                    <TabsTrigger value="en" className="flex-1 data-[state=active]:bg-[#7C3AED] data-[state=active]:text-white text-[#888] rounded-md">🇬🇧 English</TabsTrigger>
                  </TabsList>

                  <TabsContent value="fr" className="space-y-3 mt-3">
                    <Field label="Sujet">
                      <Input
                        value={subjectFr} onChange={(e) => setSubjectFr(e.target.value)}
                        className="bg-[#1E1E2E] border-[#1E1E2E] text-white rounded-[10px]"
                      />
                    </Field>
                    <Field label="Corps">
                      <Textarea
                        rows={9} value={bodyFr} onChange={(e) => setBodyFr(e.target.value)}
                        placeholder="Bonjour {{client_name}}, ..."
                        className="bg-[#1E1E2E] border-[#1E1E2E] text-white placeholder:text-[#888] rounded-[10px] resize-none font-mono text-[13px]"
                      />
                    </Field>
                  </TabsContent>

                  <TabsContent value="en" className="space-y-3 mt-3">
                    <Field label="Subject">
                      <Input
                        value={subjectEn} onChange={(e) => setSubjectEn(e.target.value)}
                        className="bg-[#1E1E2E] border-[#1E1E2E] text-white rounded-[10px]"
                      />
                    </Field>
                    <Field label="Body">
                      <Textarea
                        rows={9} value={bodyEn} onChange={(e) => setBodyEn(e.target.value)}
                        placeholder="Hello {{client_name}}, ..."
                        className="bg-[#1E1E2E] border-[#1E1E2E] text-white placeholder:text-[#888] rounded-[10px] resize-none font-mono text-[13px]"
                      />
                    </Field>
                  </TabsContent>
                </Tabs>

                {/* Personalization tokens */}
                <div>
                  <div className="text-[10px] uppercase tracking-[2px] text-[#888] mb-1.5">
                    Personnalisation — cliquez pour insérer
                  </div>
                  <div className="flex flex-wrap gap-1.5">
                    {PERSONALIZATION_TOKENS.map((t) => (
                      <button
                        key={t.token}
                        type="button"
                        onClick={() => insertToken(t.token)}
                        className="text-[11px] px-2 py-1 rounded-md bg-[#1E1E2E] hover:bg-[#7C3AED33] text-[#888] hover:text-white border border-[#1E1E2E] hover:border-[#7C3AED] transition"
                        title={t.label}
                      >
                        <code>{t.token}</code>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Schedule */}
                <Field label="Planification">
                  <Select value={scheduleNow} onValueChange={(v) => setScheduleNow(v as any)}>
                    <SelectTrigger className="bg-[#1E1E2E] border-[#1E1E2E] text-white rounded-[10px]">
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent className="bg-[#0D0D1A] border-[#1E1E2E] text-white">
                      <SelectItem value="now">Envoyer maintenant</SelectItem>
                      <SelectItem value="later">Planifier plus tard</SelectItem>
                    </SelectContent>
                  </Select>
                  {scheduleNow === "later" && (
                    <div className="mt-2 space-y-2">
                      <Input
                        type="datetime-local"
                        value={scheduledAt}
                        onChange={(e) => setScheduledAt(e.target.value)}
                        className="bg-[#1E1E2E] border-[#1E1E2E] text-white rounded-[10px]"
                      />
                      <p className="text-[11px] text-[#7C3AED] flex items-center gap-1.5">
                        <Sparkles className="h-3 w-3" /> Heure optimale suggérée : {optimalHint}
                      </p>
                    </div>
                  )}
                </Field>

                {/* Test send */}
                <div className="rounded-[10px] border border-[#1E1E2E] bg-[#0a0a14] p-3">
                  <div className="text-[10px] uppercase tracking-[2px] text-[#888] mb-2">Test avant envoi</div>
                  <div className="flex gap-2">
                    <Input
                      value={testEmail} onChange={(e) => setTestEmail(e.target.value)}
                      placeholder="email@nivra-telecom.ca"
                      className="bg-[#1E1E2E] border-[#1E1E2E] text-white rounded-[10px] h-9 text-sm flex-1"
                    />
                    <Button
                      onClick={handleSendTest} disabled={sendingTest}
                      variant="outline"
                      className="rounded-[10px] border-[#7C3AED] text-[#7C3AED] hover:bg-[#7C3AED15] hover:text-white h-9"
                    >
                      {sendingTest ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <TestTube2 className="h-3.5 w-3.5 mr-1" />}
                      Envoyer test
                    </Button>
                  </div>
                </div>

                {/* Actions */}
                <div className="grid grid-cols-2 gap-2">
                  <Button
                    onClick={handleSaveDraft} disabled={savingDraft || creating}
                    variant="outline"
                    className="rounded-[10px] border-[#1E1E2E] text-white hover:bg-[#1E1E2E] h-11"
                  >
                    {savingDraft ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> : <Save className="h-4 w-4 mr-2" />}
                    Enregistrer brouillon
                  </Button>
                  <Button
                    onClick={handleCreate} disabled={creating || savingDraft}
                    className="rounded-[10px] text-white border-0 h-11 font-semibold"
                    style={{ background: "#7C3AED" }}
                  >
                    {creating ? <Loader2 className="h-4 w-4 animate-spin mr-2" /> :
                      scheduleNow === "now" ? <Send className="h-4 w-4 mr-2" /> : <Calendar className="h-4 w-4 mr-2" />}
                    {scheduleNow === "now" ? "Envoyer" : "Planifier"}
                  </Button>
                </div>
              </div>
            </MKCard>

            {/* Live preview */}
            <MKCard>
              <MKCardHeader title="Aperçu corporate · #0066CC" />
              <div className="p-5">
                <div className="rounded-[10px] overflow-hidden border border-[#1E1E2E] bg-[#f4f6fa]">
                  <div style={{ background: "#0066CC", color: "white", padding: "20px", textAlign: "center", fontSize: 18, fontWeight: 700, fontFamily: "Arial, sans-serif" }}>
                    Nivra Télécom
                  </div>
                  <div style={{ background: "white", color: "#1a1a1a", padding: 24, fontFamily: "Arial, sans-serif", fontSize: 14, lineHeight: 1.6, minHeight: 240 }}>
                    {(lang === "fr" ? subjectFr : subjectEn) && (
                      <div style={{ fontSize: 16, fontWeight: 600, marginBottom: 12, color: "#0066CC" }}>
                        {lang === "fr" ? subjectFr : subjectEn}
                      </div>
                    )}
                    <div style={{ whiteSpace: "pre-wrap" }}>
                      {(lang === "fr" ? bodyFr : bodyEn) ||
                        <span style={{ color: "#9ca3af" }}>(votre message apparaîtra ici)</span>}
                    </div>
                  </div>
                  <div style={{ background: "#f4f6fa", padding: 12, textAlign: "center", color: "#6b7280", fontSize: 11, fontFamily: "Arial, sans-serif" }}>
                    © {new Date().getFullYear()} Nivra Télécom · Vous recevez cet email car vous êtes client Nivra.<br />
                    <span style={{ color: "#0066CC", textDecoration: "underline" }}>Se désabonner</span> · <span style={{ color: "#0066CC", textDecoration: "underline" }}>support@nivra-telecom.ca</span>
                  </div>
                </div>

                <div className="mt-4 p-3 rounded-[10px] bg-[#10B98115] border border-[#10B98133]">
                  <div className="text-[10px] uppercase tracking-[2px] text-[#10B981] font-semibold mb-1">Anti-spam intégré</div>
                  <ul className="text-[11px] text-[#888] space-y-0.5 list-disc pl-4">
                    <li>Lien de désabonnement obligatoire dans chaque email</li>
                    <li>Header List-Unsubscribe (one-click) ajouté</li>
                    <li>Désabonnés exclus automatiquement</li>
                    <li>File d'envoi avec rate-limiting natif</li>
                    <li>Version texte générée automatiquement</li>
                  </ul>
                </div>
              </div>
            </MKCard>
          </div>
        </TabsContent>

        {/* ─── Templates ─────────────────────────────────────────────── */}
        <TabsContent value="templates" className="mt-4 space-y-4">
          <MKCard>
            <MKCardHeader title="Templates pré-construits" />
            <div className="p-4 grid sm:grid-cols-2 gap-3">
              {PREBUILT_TEMPLATES.map((t) => (
                <div
                  key={t.key}
                  className="rounded-[10px] border border-[#1E1E2E] bg-[#0a0a14] p-4 hover:border-[#7C3AED66] transition"
                >
                  <div className="flex items-start justify-between gap-2 mb-2">
                    <h3 className="font-semibold text-white text-sm">{t.title}</h3>
                    <Badge className="bg-[#7C3AED22] text-[#7C3AED] border-0 text-[10px] uppercase">FR/EN</Badge>
                  </div>
                  <p className="text-xs text-[#888] mb-3 line-clamp-2">{t.subjectFr}</p>
                  <Button
                    size="sm" onClick={() => applyPrebuilt(t)}
                    className="w-full rounded-[10px] bg-[#1E1E2E] hover:bg-[#7C3AED] text-white border-0 h-8"
                  >
                    Utiliser ce template
                  </Button>
                </div>
              ))}
            </div>
          </MKCard>

          <MKCard>
            <MKCardHeader title={`Templates sauvegardés · ${templates.length}`} />
            <div className="p-2">
              {templates.length === 0 ? (
                <Empty icon={FileText} text="Aucun template enregistré" />
              ) : (
                <div className="space-y-1.5">
                  {templates.map((t) => (
                    <div key={t.id} className="flex items-center justify-between p-3 rounded-[10px] border border-[#1E1E2E] bg-[#0a0a14]">
                      <div className="min-w-0">
                        <div className="text-sm font-medium text-white truncate">{t.name}</div>
                        <div className="text-[11px] text-[#888] truncate">{t.subject}</div>
                      </div>
                      <span className="text-[10px] text-[#666] tabular-nums whitespace-nowrap ml-2">
                        {format(new Date(t.created_at), "d MMM", { locale: frLocale })}
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </MKCard>
        </TabsContent>

        {/* ─── Unsubscribes ──────────────────────────────────────────── */}
        <TabsContent value="unsubs" className="mt-4">
          <MKCard>
            <MKCardHeader title={`Liste de suppression · ${unsubs.filter(u => u.is_active).length} actifs`} />
            <div className="p-2">
              {unsubs.length === 0 ? (
                <Empty icon={Ban} text="Aucun désabonnement enregistré" />
              ) : (
                <div className="space-y-1.5">
                  {unsubs.map((u) => (
                    <div key={u.id} className="flex items-center justify-between gap-3 p-3 rounded-[10px] border border-[#1E1E2E] bg-[#0a0a14]">
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="text-sm font-medium text-white truncate">{u.email}</span>
                          {u.is_active ? (
                            <Badge className="bg-[#EF444422] text-[#EF4444] border-0 text-[10px]">Désabonné</Badge>
                          ) : (
                            <Badge className="bg-[#10B98122] text-[#10B981] border-0 text-[10px]">Ré-abonné</Badge>
                          )}
                          {u.reason && (
                            <Badge className="bg-[#1E1E2E] text-[#888] border-0 text-[10px] uppercase">{u.reason}</Badge>
                          )}
                        </div>
                        <div className="text-[11px] text-[#666] mt-0.5">
                          {format(new Date(u.unsubscribed_at), "d MMM yyyy HH:mm", { locale: frLocale })}
                          {u.source && ` · ${u.source}`}
                        </div>
                      </div>
                      {u.is_active && (
                        <Button
                          size="sm" variant="outline"
                          onClick={() => handleResubscribe(u.id, u.email)}
                          className="rounded-[10px] border-[#1E1E2E] text-[#10B981] hover:bg-[#10B98115] hover:text-[#10B981] h-8"
                        >
                          <RotateCcw className="h-3 w-3 mr-1" /> Ré-abonner
                        </Button>
                      )}
                    </div>
                  ))}
                </div>
              )}
            </div>
          </MKCard>
        </TabsContent>

        {/* ─── Stats ─────────────────────────────────────────────────── */}
        <TabsContent value="stats" className="mt-4 space-y-4">
          <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
            <MKStat label="Emails envoyés" value={stats.totalSent} icon={Send} accent="#7C3AED" />
            <MKStat label="Taux d'ouverture" value={`${stats.openRate}%`} icon={Eye} accent="#10B981" />
            <MKStat label="Taux de clic" value={`${stats.clickRate}%`} icon={MousePointer} accent="#F59E0B" />
            <MKStat label="Désabonnés actifs" value={stats.activeUnsubs} icon={Ban} accent="#EF4444" />
          </div>

          <MKCard>
            <MKCardHeader title="Ouvertures & clics — 30 derniers jours" />
            <div className="p-4" style={{ height: 280 }}>
              <ResponsiveContainer width="100%" height="100%">
                <LineChart data={opensTimeline}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#1E1E2E" />
                  <XAxis dataKey="date" stroke="#888" fontSize={11} />
                  <YAxis stroke="#888" fontSize={11} allowDecimals={false} />
                  <Tooltip
                    contentStyle={{ background: "#0D0D1A", border: "1px solid #1E1E2E", borderRadius: 8, color: "#fff", fontSize: 12 }}
                    labelStyle={{ color: "#888" }}
                  />
                  <Line type="monotone" dataKey="opens" stroke="#10B981" strokeWidth={2} dot={false} name="Ouvertures" />
                  <Line type="monotone" dataKey="clicks" stroke="#F59E0B" strokeWidth={2} dot={false} name="Clics" />
                </LineChart>
              </ResponsiveContainer>
            </div>
          </MKCard>

          <MKCard>
            <MKCardHeader title="Performance par campagne" />
            <div className="p-2">
              {campaigns.length === 0 ? (
                <Empty icon={BarChart3} text="Aucune donnée" />
              ) : (
                <div className="space-y-2">
                  {campaigns.slice(0, 20).map((c) => <CampaignRow key={c.id} c={c} />)}
                </div>
              )}
            </div>
          </MKCard>
        </TabsContent>
      </Tabs>
    </MKPage>
  );
};

// ─── Sub-components ────────────────────────────────────────────────────────

function TabTrigger({ value, icon: Icon, children }: { value: string; icon: any; children: React.ReactNode }) {
  return (
    <TabsTrigger
      value={value}
      className="data-[state=active]:bg-[#7C3AED] data-[state=active]:text-white text-[#888] rounded-md text-xs h-8 px-3"
    >
      <Icon className="h-3.5 w-3.5 mr-1.5" /> {children}
    </TabsTrigger>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <label className="text-[10px] uppercase tracking-[2px] text-[#888] mb-1.5 block">{label}</label>
      {children}
    </div>
  );
}

function SmallSelect({ label, value, onChange, options }: {
  label: string; value: string; onChange: (v: string) => void;
  options: { v: string; l: string }[];
}) {
  return (
    <div>
      <div className="text-[10px] uppercase tracking-[2px] text-[#888] mb-1">{label}</div>
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger className="bg-[#1E1E2E] border-[#1E1E2E] text-white rounded-[10px] h-9 text-sm">
          <SelectValue />
        </SelectTrigger>
        <SelectContent className="bg-[#0D0D1A] border-[#1E1E2E] text-white">
          {options.map((o) => <SelectItem key={o.v} value={o.v}>{o.l}</SelectItem>)}
        </SelectContent>
      </Select>
    </div>
  );
}

function CampaignRow({ c }: { c: Campaign }) {
  const openRate = c.total_sent > 0 ? Math.round((c.total_opened / c.total_sent) * 100) : 0;
  const clickRate = c.total_sent > 0 ? Math.round((c.total_clicked / c.total_sent) * 100) : 0;
  const statusStyle =
    c.status === "sent" || c.status === "completed"
      ? { background: "#10B98122", color: "#10B981" }
      : c.status === "sending"
        ? { background: "#F59E0B22", color: "#F59E0B" }
        : c.status === "scheduled"
          ? { background: "#7C3AED22", color: "#7C3AED" }
          : { background: "#1E1E2E", color: "#888" };
  return (
    <div className="rounded-[10px] border border-[#1E1E2E] bg-[#0a0a14] p-4 hover:border-[#7C3AED66] transition">
      <div className="flex items-start justify-between gap-4 flex-wrap">
        <div className="flex-1 min-w-[200px]">
          <div className="flex items-center gap-2 flex-wrap">
            <h3 className="font-semibold text-white truncate">{c.name}</h3>
            <span className="text-[10px] px-2 py-0.5 rounded font-semibold uppercase tracking-wider" style={statusStyle}>
              {c.status}
            </span>
            {c.campaign_number && (
              <span className="text-[10px] text-[#666] font-mono">#{c.campaign_number}</span>
            )}
          </div>
          <p className="text-sm text-[#888] truncate mt-1">{c.subject_override}</p>
          <p className="text-[11px] text-[#666] mt-1">
            {format(new Date(c.created_at), "d MMM yyyy HH:mm", { locale: frLocale })}
            {c.scheduled_at && ` · planifié ${format(new Date(c.scheduled_at), "d MMM HH:mm", { locale: frLocale })}`}
          </p>
        </div>
        <div className="grid grid-cols-5 gap-3 text-center">
          <Stat label="Cibles" value={c.total_recipients} icon={Users} color="#888" />
          <Stat label="Envoyés" value={c.total_sent} icon={Send} color="#888" />
          <Stat label="Ouverts" value={`${openRate}%`} icon={Eye} color="#10B981" />
          <Stat label="Cliqués" value={`${clickRate}%`} icon={MousePointer} color="#F59E0B" />
          <Stat label="Désabo." value={c.total_unsubscribed} icon={Ban} color="#EF4444" />
        </div>
      </div>
    </div>
  );
}

function Stat({ label, value, icon: Icon, color }: { label: string; value: any; icon: any; color: string }) {
  return (
    <div>
      <div className="text-sm font-bold text-white inline-flex items-center justify-center gap-1 tabular-nums">
        <Icon className="h-3 w-3" style={{ color }} />
        {value}
      </div>
      <div className="text-[10px] text-[#888] uppercase tracking-wider mt-0.5">{label}</div>
    </div>
  );
}

function Loading() {
  return (
    <div className="text-center py-12 text-[#888]">
      <Loader2 className="h-5 w-5 animate-spin inline" />
    </div>
  );
}

function Empty({ icon: Icon, text }: { icon: any; text: string }) {
  return (
    <div className="text-center py-12 text-sm text-[#888]">
      <Icon className="h-8 w-8 mx-auto mb-2 opacity-50" />
      {text}
    </div>
  );
}

export default MarketingEmailCampaignsPage;
