-- ============================================================================
-- V2.4: Contract Auto-Generation System
-- Adds order_id, version, status columns to contracts table
-- Creates trigger to auto-generate contract when order payment is confirmed
-- ============================================================================

-- 1. Add missing columns to contracts table
ALTER TABLE public.contracts 
ADD COLUMN IF NOT EXISTS order_id uuid REFERENCES public.orders(id),
ADD COLUMN IF NOT EXISTS version integer DEFAULT 1,
ADD COLUMN IF NOT EXISTS status text DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'signed', 'void', 'superseded'));

-- 2. Create index for order lookup
CREATE INDEX IF NOT EXISTS idx_contracts_order_id ON public.contracts(order_id);
CREATE INDEX IF NOT EXISTS idx_contracts_status ON public.contracts(status);

-- 3. Function to auto-generate contract on payment confirmation
CREATE OR REPLACE FUNCTION public.auto_generate_contract_on_payment()
RETURNS TRIGGER AS $$
DECLARE
  v_contract_number text;
  v_existing_contract_id uuid;
BEGIN
  -- Only trigger when payment_status changes to 'captured' or 'paid'
  IF (TG_OP = 'UPDATE' AND 
      OLD.payment_status IS DISTINCT FROM NEW.payment_status AND
      NEW.payment_status IN ('captured', 'paid', 'confirmed')) THEN
    
    -- Check if a non-void contract already exists for this order
    SELECT id INTO v_existing_contract_id
    FROM public.contracts
    WHERE order_id = NEW.id AND status NOT IN ('void', 'superseded')
    LIMIT 1;
    
    -- If contract exists, skip (don't create duplicate)
    IF v_existing_contract_id IS NOT NULL THEN
      RAISE NOTICE 'Contract already exists for order %, skipping auto-generation', NEW.id;
      RETURN NEW;
    END IF;
    
    -- Generate secure 9-digit contract number (2-9 first digit)
    v_contract_number := (floor(random() * 8) + 2)::text || lpad(floor(random() * 100000000)::text, 8, '0');
    
    -- Create contract record
    INSERT INTO public.contracts (
      user_id,
      owner_user_id,
      contract_name,
      contract_url,
      contract_number,
      order_id,
      version,
      status,
      template_id,
      template_version,
      created_at
    ) VALUES (
      NEW.user_id,
      NEW.user_id,
      'Contrat de Service - Commande #' || NEW.confirmation_number,
      '', -- PDF URL to be generated by edge function
      v_contract_number,
      NEW.id,
      1,
      'draft',
      'contract_template_v2026_02_06',
      'v2026.02.06-01',
      now()
    );
    
    RAISE NOTICE 'Auto-created contract % for order %', v_contract_number, NEW.id;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 4. Create trigger on orders table
DROP TRIGGER IF EXISTS trg_auto_generate_contract_on_payment ON public.orders;
CREATE TRIGGER trg_auto_generate_contract_on_payment
  AFTER UPDATE ON public.orders
  FOR EACH ROW
  EXECUTE FUNCTION public.auto_generate_contract_on_payment();

-- 5. Function to supersede old contracts when creating new version
CREATE OR REPLACE FUNCTION public.supersede_contract_version(p_order_id uuid)
RETURNS uuid AS $$
DECLARE
  v_new_contract_id uuid;
  v_new_version integer;
  v_contract_number text;
BEGIN
  -- Mark all existing non-void contracts for this order as superseded
  UPDATE public.contracts
  SET status = 'superseded'
  WHERE order_id = p_order_id AND status NOT IN ('void', 'superseded');
  
  -- Get the next version number
  SELECT COALESCE(MAX(version), 0) + 1 INTO v_new_version
  FROM public.contracts
  WHERE order_id = p_order_id;
  
  -- Generate new contract number
  v_contract_number := (floor(random() * 8) + 2)::text || lpad(floor(random() * 100000000)::text, 8, '0');
  
  -- Create new version
  INSERT INTO public.contracts (
    user_id,
    owner_user_id,
    contract_name,
    contract_url,
    contract_number,
    order_id,
    version,
    status,
    template_id,
    template_version,
    created_at
  )
  SELECT 
    o.user_id,
    o.user_id,
    'Contrat de Service v' || v_new_version || ' - Commande #' || o.confirmation_number,
    '',
    v_contract_number,
    o.id,
    v_new_version,
    'draft',
    'contract_template_v2026_02_06',
    'v2026.02.06-01',
    now()
  FROM public.orders o
  WHERE o.id = p_order_id
  RETURNING id INTO v_new_contract_id;
  
  RETURN v_new_contract_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- 6. Grant execute permission
GRANT EXECUTE ON FUNCTION public.supersede_contract_version(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.auto_generate_contract_on_payment() TO authenticated;