-- 1. Extend service_coverage_areas
ALTER TABLE public.service_coverage_areas
  ADD COLUMN IF NOT EXISTS city TEXT,
  ADD COLUMN IF NOT EXISTS province TEXT NOT NULL DEFAULT 'QC',
  ADD COLUMN IF NOT EXISTS internet_available BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS internet_max_speed TEXT NOT NULL DEFAULT '1 Gbps',
  ADD COLUMN IF NOT EXISTS tv_available BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS mobile_available BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS network_provider TEXT NOT NULL DEFAULT 'Bell';

CREATE INDEX IF NOT EXISTS idx_coverage_postal_prefix ON public.service_coverage_areas(postal_prefix);
CREATE INDEX IF NOT EXISTS idx_coverage_province ON public.service_coverage_areas(province);

-- Backfill booleans from existing available_services JSONB (best-effort)
UPDATE public.service_coverage_areas
SET
  internet_available = COALESCE((available_services::jsonb ? 'internet') OR (available_services::jsonb ? 'Internet'), internet_available),
  tv_available       = COALESCE((available_services::jsonb ? 'tv')       OR (available_services::jsonb ? 'TV'),       tv_available),
  mobile_available   = COALESCE((available_services::jsonb ? 'mobile')   OR (available_services::jsonb ? 'Mobile'),   mobile_available)
WHERE available_services IS NOT NULL;

-- 2. Seed FSAs (idempotent). coverage_type 'full' = available everywhere.
INSERT INTO public.service_coverage_areas
  (postal_prefix, city, province, coverage_type, internet_available, tv_available, mobile_available, network_provider, is_active)
VALUES
  ('H1A','Montréal-Est','QC','full',true,true,true,'Bell',true),('H1B','Montréal','QC','full',true,true,true,'Bell',true),('H1C','Montréal','QC','full',true,true,true,'Bell',true),('H1E','Montréal','QC','full',true,true,true,'Bell',true),('H1G','Montréal','QC','full',true,true,true,'Bell',true),('H1H','Montréal','QC','full',true,true,true,'Bell',true),('H1J','Montréal','QC','full',true,true,true,'Bell',true),('H1K','Montréal','QC','full',true,true,true,'Bell',true),('H1L','Montréal','QC','full',true,true,true,'Bell',true),('H1M','Montréal','QC','full',true,true,true,'Bell',true),('H1N','Montréal','QC','full',true,true,true,'Bell',true),('H1P','Montréal','QC','full',true,true,true,'Bell',true),('H1R','Montréal','QC','full',true,true,true,'Bell',true),('H1S','Montréal','QC','full',true,true,true,'Bell',true),('H1T','Montréal','QC','full',true,true,true,'Bell',true),('H1V','Montréal','QC','full',true,true,true,'Bell',true),('H1W','Montréal','QC','full',true,true,true,'Bell',true),('H1X','Montréal','QC','full',true,true,true,'Bell',true),('H1Y','Montréal','QC','full',true,true,true,'Bell',true),('H1Z','Montréal','QC','full',true,true,true,'Bell',true),
  ('H2A','Montréal','QC','full',true,true,true,'Bell',true),('H2B','Montréal','QC','full',true,true,true,'Bell',true),('H2C','Montréal','QC','full',true,true,true,'Bell',true),('H2E','Montréal','QC','full',true,true,true,'Bell',true),('H2G','Montréal','QC','full',true,true,true,'Bell',true),('H2H','Montréal','QC','full',true,true,true,'Bell',true),('H2J','Montréal','QC','full',true,true,true,'Bell',true),('H2K','Montréal','QC','full',true,true,true,'Bell',true),('H2L','Montréal','QC','full',true,true,true,'Bell',true),('H2M','Montréal','QC','full',true,true,true,'Bell',true),('H2N','Montréal','QC','full',true,true,true,'Bell',true),('H2P','Montréal','QC','full',true,true,true,'Bell',true),('H2R','Montréal','QC','full',true,true,true,'Bell',true),('H2S','Montréal','QC','full',true,true,true,'Bell',true),('H2T','Montréal','QC','full',true,true,true,'Bell',true),('H2V','Montréal','QC','full',true,true,true,'Bell',true),('H2W','Montréal','QC','full',true,true,true,'Bell',true),('H2X','Montréal','QC','full',true,true,true,'Bell',true),('H2Y','Montréal','QC','full',true,true,true,'Bell',true),('H2Z','Montréal','QC','full',true,true,true,'Bell',true),
  ('H3A','Montréal','QC','full',true,true,true,'Bell',true),('H3B','Montréal','QC','full',true,true,true,'Bell',true),('H3C','Montréal','QC','full',true,true,true,'Bell',true),('H3E','Montréal','QC','full',true,true,true,'Bell',true),('H3G','Montréal','QC','full',true,true,true,'Bell',true),('H3H','Montréal','QC','full',true,true,true,'Bell',true),('H3J','Montréal','QC','full',true,true,true,'Bell',true),('H3K','Montréal','QC','full',true,true,true,'Bell',true),('H3L','Montréal','QC','full',true,true,true,'Bell',true),('H3M','Montréal','QC','full',true,true,true,'Bell',true),('H3N','Montréal','QC','full',true,true,true,'Bell',true),('H3P','Montréal','QC','full',true,true,true,'Bell',true),('H3R','Montréal','QC','full',true,true,true,'Bell',true),('H3S','Montréal','QC','full',true,true,true,'Bell',true),('H3T','Montréal','QC','full',true,true,true,'Bell',true),('H3V','Montréal','QC','full',true,true,true,'Bell',true),('H3W','Montréal','QC','full',true,true,true,'Bell',true),('H3X','Montréal','QC','full',true,true,true,'Bell',true),('H3Y','Montréal','QC','full',true,true,true,'Bell',true),('H3Z','Montréal','QC','full',true,true,true,'Bell',true),
  ('H4A','Montréal','QC','full',true,true,true,'Bell',true),('H4B','Montréal','QC','full',true,true,true,'Bell',true),('H4C','Montréal','QC','full',true,true,true,'Bell',true),('H4E','Montréal','QC','full',true,true,true,'Bell',true),('H4G','Montréal','QC','full',true,true,true,'Bell',true),('H4H','Montréal','QC','full',true,true,true,'Bell',true),('H4J','Montréal','QC','full',true,true,true,'Bell',true),('H4K','Montréal','QC','full',true,true,true,'Bell',true),('H4L','Montréal','QC','full',true,true,true,'Bell',true),('H4M','Montréal','QC','full',true,true,true,'Bell',true),('H4N','Montréal','QC','full',true,true,true,'Bell',true),('H4P','Montréal','QC','full',true,true,true,'Bell',true),('H4R','Montréal','QC','full',true,true,true,'Bell',true),('H4S','Montréal','QC','full',true,true,true,'Bell',true),('H4T','Montréal','QC','full',true,true,true,'Bell',true),('H4V','Montréal','QC','full',true,true,true,'Bell',true),('H4W','Montréal','QC','full',true,true,true,'Bell',true),('H4X','Montréal','QC','full',true,true,true,'Bell',true),('H4Y','Montréal','QC','full',true,true,true,'Bell',true),('H4Z','Montréal','QC','full',true,true,true,'Bell',true),
  ('H5A','Montréal','QC','full',true,true,true,'Bell',true),('H5B','Montréal','QC','full',true,true,true,'Bell',true),
  ('H7A','Laval','QC','full',true,true,true,'Bell',true),('H7B','Laval','QC','full',true,true,true,'Bell',true),('H7C','Laval','QC','full',true,true,true,'Bell',true),('H7E','Laval','QC','full',true,true,true,'Bell',true),('H7G','Laval','QC','full',true,true,true,'Bell',true),('H7H','Laval','QC','full',true,true,true,'Bell',true),('H7J','Laval','QC','full',true,true,true,'Bell',true),('H7K','Laval','QC','full',true,true,true,'Bell',true),('H7L','Laval','QC','full',true,true,true,'Bell',true),('H7M','Laval','QC','full',true,true,true,'Bell',true),('H7N','Laval','QC','full',true,true,true,'Bell',true),('H7P','Laval','QC','full',true,true,true,'Bell',true),('H7R','Laval','QC','full',true,true,true,'Bell',true),('H7S','Laval','QC','full',true,true,true,'Bell',true),('H7T','Laval','QC','full',true,true,true,'Bell',true),('H7V','Laval','QC','full',true,true,true,'Bell',true),('H7W','Laval','QC','full',true,true,true,'Bell',true),('H7X','Laval','QC','full',true,true,true,'Bell',true),('H7Y','Laval','QC','full',true,true,true,'Bell',true),
  ('H8N','LaSalle','QC','full',true,true,true,'Bell',true),('H8P','LaSalle','QC','full',true,true,true,'Bell',true),('H8R','LaSalle','QC','full',true,true,true,'Bell',true),('H8S','LaSalle','QC','full',true,true,true,'Bell',true),('H8T','LaSalle','QC','full',true,true,true,'Bell',true),('H8Y','Dollard-des-Ormeaux','QC','full',true,true,true,'Bell',true),('H8Z','Dollard-des-Ormeaux','QC','full',true,true,true,'Bell',true),
  ('H9A','Dollard-des-Ormeaux','QC','full',true,true,true,'Bell',true),('H9B','Dollard-des-Ormeaux','QC','full',true,true,true,'Bell',true),('H9C','Kirkland','QC','full',true,true,true,'Bell',true),('H9E','Kirkland','QC','full',true,true,true,'Bell',true),('H9G','Pierrefonds','QC','full',true,true,true,'Bell',true),('H9H','Pierrefonds','QC','full',true,true,true,'Bell',true),('H9J','Pierrefonds','QC','full',true,true,true,'Bell',true),('H9K','Pierrefonds','QC','full',true,true,true,'Bell',true),('H9P','Dorval','QC','full',true,true,true,'Bell',true),('H9R','Pointe-Claire','QC','full',true,true,true,'Bell',true),('H9S','Pointe-Claire','QC','full',true,true,true,'Bell',true),('H9W','Sainte-Anne-de-Bellevue','QC','full',true,true,true,'Bell',true),('H9X','Sainte-Anne-de-Bellevue','QC','full',true,true,true,'Bell',true),
  ('J0A','Québec région','QC','full',true,true,true,'Bell',true),('J0B','Québec région','QC','full',true,true,true,'Bell',true),('J0C','Québec région','QC','full',true,true,true,'Bell',true),('J0E','Québec région','QC','full',true,true,true,'Bell',true),('J0G','Québec région','QC','full',true,true,true,'Bell',true),('J0H','Québec région','QC','full',true,true,true,'Bell',true),('J0J','Québec région','QC','full',true,true,true,'Bell',true),('J0K','Québec région','QC','full',true,true,true,'Bell',true),('J0L','Québec région','QC','full',true,true,true,'Bell',true),('J0M','Québec région','QC','full',true,true,true,'Bell',true),('J0N','Québec région','QC','full',true,true,true,'Bell',true),('J0P','Québec région','QC','full',true,true,true,'Bell',true),('J0R','Québec région','QC','full',true,true,true,'Bell',true),('J0S','Québec région','QC','full',true,true,true,'Bell',true),('J0T','Québec région','QC','full',true,true,true,'Bell',true),('J0V','Québec région','QC','full',true,true,true,'Bell',true),('J0W','Québec région','QC','full',true,true,true,'Bell',true),('J0X','Québec région','QC','full',true,true,true,'Bell',true),('J0Y','Québec région','QC','full',true,true,true,'Bell',true),('J0Z','Québec région','QC','full',true,true,true,'Bell',true),
  ('J1A','Québec','QC','full',true,true,true,'Bell',true),('J1C','Québec','QC','full',true,true,true,'Bell',true),('J1E','Québec','QC','full',true,true,true,'Bell',true),('J1G','Québec','QC','full',true,true,true,'Bell',true),('J1H','Québec','QC','full',true,true,true,'Bell',true),('J1J','Québec','QC','full',true,true,true,'Bell',true),('J1K','Québec','QC','full',true,true,true,'Bell',true),('J1L','Québec','QC','full',true,true,true,'Bell',true),('J1M','Québec','QC','full',true,true,true,'Bell',true),('J1N','Québec','QC','full',true,true,true,'Bell',true),('J1R','Québec','QC','full',true,true,true,'Bell',true),('J1S','Québec','QC','full',true,true,true,'Bell',true),('J1T','Québec','QC','full',true,true,true,'Bell',true),('J1X','Québec','QC','full',true,true,true,'Bell',true),
  ('J2A','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2B','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2C','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2E','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2G','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2H','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2J','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2K','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2L','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2N','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2R','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2S','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2T','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2W','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2X','Rive-Sud','QC','full',true,true,true,'Bell',true),('J2Y','Rive-Sud','QC','full',true,true,true,'Bell',true),
  ('J3A','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3B','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3E','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3G','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3H','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3L','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3M','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3N','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3P','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3R','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3T','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3V','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3X','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3Y','Rive-Sud','QC','full',true,true,true,'Bell',true),('J3Z','Rive-Sud','QC','full',true,true,true,'Bell',true),
  ('J4B','Longueuil','QC','full',true,true,true,'Bell',true),('J4G','Longueuil','QC','full',true,true,true,'Bell',true),('J4H','Longueuil','QC','full',true,true,true,'Bell',true),('J4J','Longueuil','QC','full',true,true,true,'Bell',true),('J4K','Longueuil','QC','full',true,true,true,'Bell',true),('J4L','Longueuil','QC','full',true,true,true,'Bell',true),('J4M','Longueuil','QC','full',true,true,true,'Bell',true),('J4N','Longueuil','QC','full',true,true,true,'Bell',true),('J4P','Longueuil','QC','full',true,true,true,'Bell',true),('J4R','Longueuil','QC','full',true,true,true,'Bell',true),('J4S','Longueuil','QC','full',true,true,true,'Bell',true),('J4T','Longueuil','QC','full',true,true,true,'Bell',true),('J4V','Longueuil','QC','full',true,true,true,'Bell',true),('J4W','Longueuil','QC','full',true,true,true,'Bell',true),('J4X','Longueuil','QC','full',true,true,true,'Bell',true),('J4Y','Longueuil','QC','full',true,true,true,'Bell',true),('J4Z','Longueuil','QC','full',true,true,true,'Bell',true),
  ('J5A','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5B','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5C','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5J','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5K','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5L','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5M','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5R','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5T','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5V','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5W','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5X','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5Y','Rive-Sud','QC','full',true,true,true,'Bell',true),('J5Z','Rive-Sud','QC','full',true,true,true,'Bell',true),
  ('J6A','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6E','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6J','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6K','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6N','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6R','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6S','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6T','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6V','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6W','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6X','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6Y','Rive-Sud','QC','full',true,true,true,'Bell',true),('J6Z','Rive-Sud','QC','full',true,true,true,'Bell',true),
  ('J7A','Laurentides','QC','full',true,true,true,'Bell',true),('J7B','Laurentides','QC','full',true,true,true,'Bell',true),('J7C','Laurentides','QC','full',true,true,true,'Bell',true),('J7E','Laurentides','QC','full',true,true,true,'Bell',true),('J7G','Laurentides','QC','full',true,true,true,'Bell',true),('J7H','Laurentides','QC','full',true,true,true,'Bell',true),('J7J','Laurentides','QC','full',true,true,true,'Bell',true),('J7K','Laurentides','QC','full',true,true,true,'Bell',true),('J7L','Laurentides','QC','full',true,true,true,'Bell',true),('J7M','Laurentides','QC','full',true,true,true,'Bell',true),('J7N','Laurentides','QC','full',true,true,true,'Bell',true),('J7P','Laurentides','QC','full',true,true,true,'Bell',true),('J7R','Laurentides','QC','full',true,true,true,'Bell',true),('J7T','Laurentides','QC','full',true,true,true,'Bell',true),('J7V','Laurentides','QC','full',true,true,true,'Bell',true),('J7W','Laurentides','QC','full',true,true,true,'Bell',true),('J7X','Laurentides','QC','full',true,true,true,'Bell',true),('J7Y','Laurentides','QC','full',true,true,true,'Bell',true),('J7Z','Laurentides','QC','full',true,true,true,'Bell',true),
  ('J8A','Outaouais','QC','full',true,true,true,'Bell',true),('J8B','Outaouais','QC','full',true,true,true,'Bell',true),('J8C','Outaouais','QC','full',true,true,true,'Bell',true),('J8E','Outaouais','QC','full',true,true,true,'Bell',true),('J8G','Outaouais','QC','full',true,true,true,'Bell',true),('J8H','Outaouais','QC','full',true,true,true,'Bell',true),('J8L','Outaouais','QC','full',true,true,true,'Bell',true),('J8M','Outaouais','QC','full',true,true,true,'Bell',true),('J8N','Outaouais','QC','full',true,true,true,'Bell',true),('J8P','Outaouais','QC','full',true,true,true,'Bell',true),('J8R','Outaouais','QC','full',true,true,true,'Bell',true),('J8T','Outaouais','QC','full',true,true,true,'Bell',true),('J8V','Outaouais','QC','full',true,true,true,'Bell',true),('J8X','Gatineau','QC','full',true,true,true,'Bell',true),('J8Y','Gatineau','QC','full',true,true,true,'Bell',true),('J8Z','Gatineau','QC','full',true,true,true,'Bell',true),
  ('J9A','Outaouais','QC','full',true,true,true,'Bell',true),('J9B','Outaouais','QC','full',true,true,true,'Bell',true),('J9E','Outaouais','QC','full',true,true,true,'Bell',true),('J9H','Outaouais','QC','full',true,true,true,'Bell',true),('J9J','Outaouais','QC','full',true,true,true,'Bell',true),('J9L','Outaouais','QC','full',true,true,true,'Bell',true),('J9P','Outaouais','QC','full',true,true,true,'Bell',true),('J9T','Outaouais','QC','full',true,true,true,'Bell',true),('J9V','Outaouais','QC','full',true,true,true,'Bell',true),('J9X','Rouyn-Noranda','QC','full',true,true,true,'Bell',true),('J9Y','Abitibi','QC','full',true,true,true,'Bell',true),('J9Z','Abitibi','QC','full',true,true,true,'Bell',true),
  ('G0A','Québec région','QC','full',true,true,true,'Bell',true),('G0B','Québec région','QC','full',true,true,true,'Bell',true),('G0C','Québec région','QC','full',true,true,true,'Bell',true),('G0E','Québec région','QC','full',true,true,true,'Bell',true),('G0G','Québec région','QC','full',true,true,true,'Bell',true),('G0H','Québec région','QC','full',true,true,true,'Bell',true),('G0J','Québec région','QC','full',true,true,true,'Bell',true),('G0K','Québec région','QC','full',true,true,true,'Bell',true),('G0L','Québec région','QC','full',true,true,true,'Bell',true),('G0M','Québec région','QC','full',true,true,true,'Bell',true),('G0N','Québec région','QC','full',true,true,true,'Bell',true),('G0P','Québec région','QC','full',true,true,true,'Bell',true),('G0R','Québec région','QC','full',true,true,true,'Bell',true),('G0S','Québec région','QC','full',true,true,true,'Bell',true),('G0T','Québec région','QC','full',true,true,true,'Bell',true),('G0V','Québec région','QC','full',true,true,true,'Bell',true),('G0W','Québec région','QC','full',true,true,true,'Bell',true),('G0X','Québec région','QC','full',true,true,true,'Bell',true),('G0Y','Québec région','QC','full',true,true,true,'Bell',true),('G0Z','Québec région','QC','full',true,true,true,'Bell',true),
  ('G1A','Québec City','QC','full',true,true,true,'Bell',true),('G1B','Québec City','QC','full',true,true,true,'Bell',true),('G1C','Québec City','QC','full',true,true,true,'Bell',true),('G1E','Québec City','QC','full',true,true,true,'Bell',true),('G1G','Québec City','QC','full',true,true,true,'Bell',true),('G1H','Québec City','QC','full',true,true,true,'Bell',true),('G1J','Québec City','QC','full',true,true,true,'Bell',true),('G1K','Québec City','QC','full',true,true,true,'Bell',true),('G1L','Québec City','QC','full',true,true,true,'Bell',true),('G1M','Québec City','QC','full',true,true,true,'Bell',true),('G1N','Québec City','QC','full',true,true,true,'Bell',true),('G1P','Québec City','QC','full',true,true,true,'Bell',true),('G1R','Québec City','QC','full',true,true,true,'Bell',true),('G1S','Québec City','QC','full',true,true,true,'Bell',true),('G1T','Québec City','QC','full',true,true,true,'Bell',true),('G1V','Québec City','QC','full',true,true,true,'Bell',true),('G1W','Québec City','QC','full',true,true,true,'Bell',true),('G1X','Québec City','QC','full',true,true,true,'Bell',true),('G1Y','Québec City','QC','full',true,true,true,'Bell',true),
  ('G2A','Québec City','QC','full',true,true,true,'Bell',true),('G2B','Québec City','QC','full',true,true,true,'Bell',true),('G2C','Québec City','QC','full',true,true,true,'Bell',true),('G2E','Québec City','QC','full',true,true,true,'Bell',true),('G2G','Québec City','QC','full',true,true,true,'Bell',true),('G2J','Québec City','QC','full',true,true,true,'Bell',true),('G2K','Québec City','QC','full',true,true,true,'Bell',true),('G2L','Québec City','QC','full',true,true,true,'Bell',true),('G2M','Québec City','QC','full',true,true,true,'Bell',true),('G2N','Québec City','QC','full',true,true,true,'Bell',true),
  ('G3A','Québec région','QC','full',true,true,true,'Bell',true),('G3B','Québec région','QC','full',true,true,true,'Bell',true),('G3C','Québec région','QC','full',true,true,true,'Bell',true),('G3E','Québec région','QC','full',true,true,true,'Bell',true),('G3G','Québec région','QC','full',true,true,true,'Bell',true),('G3H','Québec région','QC','full',true,true,true,'Bell',true),('G3J','Québec région','QC','full',true,true,true,'Bell',true),('G3K','Québec région','QC','full',true,true,true,'Bell',true),('G3L','Québec région','QC','full',true,true,true,'Bell',true),('G3M','Québec région','QC','full',true,true,true,'Bell',true),('G3N','Québec région','QC','full',true,true,true,'Bell',true),('G3P','Québec région','QC','full',true,true,true,'Bell',true),('G3S','Québec région','QC','full',true,true,true,'Bell',true),('G3Z','Québec région','QC','full',true,true,true,'Bell',true),
  ('G4A','Saguenay région','QC','full',true,true,true,'Bell',true),('G4R','Sept-Îles','QC','full',true,true,true,'Bell',true),('G4S','Sept-Îles','QC','full',true,true,true,'Bell',true),('G4T','Baie-Comeau','QC','full',true,true,true,'Bell',true),('G4V','Baie-Comeau','QC','full',true,true,true,'Bell',true),('G4W','Baie-Comeau','QC','full',true,true,true,'Bell',true),('G4X','Baie-Comeau','QC','full',true,true,true,'Bell',true),('G4Z','Baie-Comeau','QC','full',true,true,true,'Bell',true),
  ('G5A','Québec région','QC','full',true,true,true,'Bell',true),('G5B','Québec région','QC','full',true,true,true,'Bell',true),('G5C','Québec région','QC','full',true,true,true,'Bell',true),('G5H','Québec région','QC','full',true,true,true,'Bell',true),('G5J','Québec région','QC','full',true,true,true,'Bell',true),('G5L','Rimouski','QC','full',true,true,true,'Bell',true),('G5M','Rimouski','QC','full',true,true,true,'Bell',true),('G5N','Rimouski','QC','full',true,true,true,'Bell',true),('G5R','Rimouski','QC','full',true,true,true,'Bell',true),('G5T','Rimouski','QC','full',true,true,true,'Bell',true),('G5V','Rimouski','QC','full',true,true,true,'Bell',true),('G5X','Rimouski','QC','full',true,true,true,'Bell',true),('G5Y','Rimouski','QC','full',true,true,true,'Bell',true),('G5Z','Rimouski','QC','full',true,true,true,'Bell',true),
  ('G6A','Lévis','QC','full',true,true,true,'Bell',true),('G6B','Lévis','QC','full',true,true,true,'Bell',true),('G6C','Lévis','QC','full',true,true,true,'Bell',true),('G6E','Lévis','QC','full',true,true,true,'Bell',true),('G6G','Lévis','QC','full',true,true,true,'Bell',true),('G6H','Lévis','QC','full',true,true,true,'Bell',true),('G6J','Lévis','QC','full',true,true,true,'Bell',true),('G6K','Lévis','QC','full',true,true,true,'Bell',true),('G6L','Lévis','QC','full',true,true,true,'Bell',true),('G6P','Lévis','QC','full',true,true,true,'Bell',true),('G6R','Lévis','QC','full',true,true,true,'Bell',true),('G6S','Lévis','QC','full',true,true,true,'Bell',true),('G6T','Lévis','QC','full',true,true,true,'Bell',true),('G6V','Lévis','QC','full',true,true,true,'Bell',true),('G6W','Lévis','QC','full',true,true,true,'Bell',true),('G6X','Lévis','QC','full',true,true,true,'Bell',true),('G6Z','Lévis','QC','full',true,true,true,'Bell',true),
  ('G7A','Saguenay','QC','full',true,true,true,'Bell',true),('G7B','Saguenay','QC','full',true,true,true,'Bell',true),('G7G','Saguenay','QC','full',true,true,true,'Bell',true),('G7H','Saguenay','QC','full',true,true,true,'Bell',true),('G7J','Saguenay','QC','full',true,true,true,'Bell',true),('G7K','Saguenay','QC','full',true,true,true,'Bell',true),('G7N','Saguenay','QC','full',true,true,true,'Bell',true),('G7P','Saguenay','QC','full',true,true,true,'Bell',true),('G7S','Saguenay','QC','full',true,true,true,'Bell',true),('G7T','Saguenay','QC','full',true,true,true,'Bell',true),('G7X','Saguenay','QC','full',true,true,true,'Bell',true),('G7Z','Saguenay','QC','full',true,true,true,'Bell',true),
  ('G8A','Saguenay','QC','full',true,true,true,'Bell',true),('G8B','Saguenay','QC','full',true,true,true,'Bell',true),('G8C','Saguenay','QC','full',true,true,true,'Bell',true),('G8E','Saguenay','QC','full',true,true,true,'Bell',true),('G8G','Saguenay','QC','full',true,true,true,'Bell',true),('G8H','Saguenay','QC','full',true,true,true,'Bell',true),('G8J','Saguenay','QC','full',true,true,true,'Bell',true),('G8K','Saguenay','QC','full',true,true,true,'Bell',true),('G8L','Saguenay','QC','full',true,true,true,'Bell',true),('G8M','Saguenay','QC','full',true,true,true,'Bell',true),('G8N','Saguenay','QC','full',true,true,true,'Bell',true),('G8P','Saguenay','QC','full',true,true,true,'Bell',true),('G8T','Saguenay','QC','full',true,true,true,'Bell',true),('G8V','Saguenay','QC','full',true,true,true,'Bell',true),('G8W','Saguenay','QC','full',true,true,true,'Bell',true),('G8Y','Saguenay','QC','full',true,true,true,'Bell',true),('G8Z','Saguenay','QC','full',true,true,true,'Bell',true),
  ('G9A','Trois-Rivières','QC','full',true,true,true,'Bell',true),('G9B','Trois-Rivières','QC','full',true,true,true,'Bell',true),('G9C','Trois-Rivières','QC','full',true,true,true,'Bell',true),('G9H','Trois-Rivières','QC','full',true,true,true,'Bell',true),('G9N','Trois-Rivières','QC','full',true,true,true,'Bell',true),('G9P','Trois-Rivières','QC','full',true,true,true,'Bell',true),('G9R','Trois-Rivières','QC','full',true,true,true,'Bell',true),('G9T','Trois-Rivières','QC','full',true,true,true,'Bell',true),('G9X','Trois-Rivières','QC','full',true,true,true,'Bell',true),('G9Y','Trois-Rivières','QC','full',true,true,true,'Bell',true)
ON CONFLICT (postal_prefix) DO UPDATE
SET city = EXCLUDED.city,
    province = EXCLUDED.province,
    coverage_type = EXCLUDED.coverage_type,
    internet_available = EXCLUDED.internet_available,
    tv_available = EXCLUDED.tv_available,
    mobile_available = EXCLUDED.mobile_available,
    network_provider = EXCLUDED.network_provider,
    is_active = true,
    updated_at = now();

-- 3. coverage_waitlist table
CREATE TABLE IF NOT EXISTS public.coverage_waitlist (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL,
  postal_code TEXT,
  city TEXT,
  notes TEXT,
  notified_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_coverage_waitlist_email ON public.coverage_waitlist(email);
CREATE INDEX IF NOT EXISTS idx_coverage_waitlist_postal ON public.coverage_waitlist(postal_code);

ALTER TABLE public.coverage_waitlist ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can join coverage waitlist" ON public.coverage_waitlist;
CREATE POLICY "Anyone can join coverage waitlist"
  ON public.coverage_waitlist
  FOR INSERT
  TO public
  WITH CHECK (true);

DROP POLICY IF EXISTS "Admins manage coverage waitlist" ON public.coverage_waitlist;
CREATE POLICY "Admins manage coverage waitlist"
  ON public.coverage_waitlist
  FOR ALL
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));

-- 4. Public read + admin write on service_coverage_areas
ALTER TABLE public.service_coverage_areas ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read coverage zones" ON public.service_coverage_areas;
CREATE POLICY "Public can read coverage zones"
  ON public.service_coverage_areas
  FOR SELECT
  TO public
  USING (true);

DROP POLICY IF EXISTS "Admins manage coverage zones" ON public.service_coverage_areas;
CREATE POLICY "Admins manage coverage zones"
  ON public.service_coverage_areas
  FOR ALL
  TO authenticated
  USING (public.has_role(auth.uid(), 'admin'))
  WITH CHECK (public.has_role(auth.uid(), 'admin'));