
-- Fix: Drop the old conflicting trigger and keep only the correct one
DROP TRIGGER IF EXISTS trg_auto_create_contract_on_payment ON orders;
DROP FUNCTION IF EXISTS auto_create_contract_on_payment();

-- Ensure the correct trigger is properly set up
CREATE OR REPLACE FUNCTION auto_generate_contract_on_payment()
RETURNS TRIGGER AS $$
DECLARE
  v_contract_number text;
  v_existing_contract_id uuid;
BEGIN
  -- Only trigger when payment_status TRANSITIONS TO 'captured', 'paid', or 'confirmed'
  -- This prevents duplicate contracts on every update
  IF (TG_OP = 'UPDATE' AND 
      OLD.payment_status IS DISTINCT FROM NEW.payment_status AND
      NEW.payment_status IN ('captured', 'paid', 'confirmed') AND
      OLD.payment_status NOT IN ('captured', 'paid', 'confirmed')) THEN
    
    -- Check if a non-void contract already exists for this order
    SELECT id INTO v_existing_contract_id
    FROM public.contracts
    WHERE order_id = NEW.id AND status NOT IN ('void', 'superseded')
    LIMIT 1;
    
    -- If contract exists, skip (don't create duplicate)
    IF v_existing_contract_id IS NOT NULL THEN
      RAISE NOTICE 'Contract already exists for order %, skipping auto-generation', NEW.id;
      RETURN NEW;
    END IF;
    
    -- Generate secure 9-digit contract number (2-9 first digit)
    v_contract_number := (floor(random() * 8) + 2)::text || lpad(floor(random() * 100000000)::text, 8, '0');
    
    -- Create contract record
    INSERT INTO public.contracts (
      user_id,
      owner_user_id,
      contract_name,
      contract_url,
      contract_number,
      order_id,
      version,
      status,
      template_id,
      template_version,
      created_at
    ) VALUES (
      NEW.user_id,
      NEW.user_id,
      'Contrat de Service - Commande #' || COALESCE(NEW.confirmation_number, NEW.id::text),
      '', -- PDF URL to be generated by edge function later
      v_contract_number,
      NEW.id,
      1,
      'draft',
      'contract_template_v2026_02_06',
      'v2026.02.06-01',
      now()
    );
    
    RAISE NOTICE 'Auto-created contract % for order %', v_contract_number, NEW.id;
  END IF;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Ensure only one trigger exists
DROP TRIGGER IF EXISTS trg_auto_generate_contract_on_payment ON orders;
CREATE TRIGGER trg_auto_generate_contract_on_payment
  AFTER UPDATE ON orders
  FOR EACH ROW
  EXECUTE FUNCTION auto_generate_contract_on_payment();
