/**
 * ClientReferrals — Premium client portal referral program page
 * - Code source: referral_codes (owner_user_id) — generated by trigger
 * - Program: 25$/mo discount × 10 months for the referrer, qualified after 2 paid cycles
 * - Reward payout preference: Interac e-Transfer / Carte-cadeau Visa-Mastercard
 */
import { useEffect, useMemo, useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import ClientLayout from "@/components/client/ClientLayout";
import { portalClient } from "@/integrations/backend/portalClient";
import { useCanonicalClientData } from "@/hooks/useCanonicalClientData";
import { useLoyaltyReferralRealtime } from "@/hooks/useLoyaltyReferralRealtime";
import { useClientAuth } from "@/hooks/useClientAuth";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Gift, Copy, Users, Clock, CheckCircle, DollarSign, Share2,
  ArrowRight, CreditCard, TrendingUp, MessageCircle, Mail,
  Smartphone, Link as LinkIcon, Wallet,
} from "lucide-react";
import { toast } from "sonner";
import { Link } from "react-router-dom";

const STATUS_LABELS: Record<string, string> = {
  pending: "Code utilisé",
  code_used: "Code utilisé",
  order_created: "Commande créée",
  service_activated: "Service activé",
  cycle_1_paid: "Facture 1 payée",
  cycle_2_paid: "Facture 2 payée",
  cycle_3_paid: "Facture 3 payée",
  qualified: "Qualifié",
  reward_pending: "Récompense en attente",
  reward_issued: "Récompense envoyée",
  cancelled: "Annulé",
  disqualified: "Disqualifié",
  fraud_review: "En révision",
};

const PAYMENT_LABELS: Record<string, string> = {
  paypal: "Interac e-Transfer",
  interac: "Interac e-Transfer",
  gift_card: "Carte-cadeau Visa/Mastercard",
};

const PAYMENT_OPTIONS = [
  { value: "interac", label: "Interac e-Transfer", desc: "Envoi par courriel sécurisé" },
  { value: "gift_card", label: "Carte-cadeau Visa/Mastercard", desc: "Carte prépayée par courriel" },
] as const;

function getStatusColor(status: string) {
  if (["qualified", "reward_pending", "reward_issued"].includes(status))
    return "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400";
  if (["cancelled", "disqualified", "fraud_review"].includes(status))
    return "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400";
  return "bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-400";
}

function CycleProgress({ paid, total }: { paid: number; total: number }) {
  const safeTotal = Math.max(total || 3, 1);
  return (
    <div className="flex gap-1.5 items-center">
      {Array.from({ length: safeTotal }, (_, i) => (
        <div key={i} className="flex flex-col items-center gap-0.5">
          <div
            className={`w-8 h-2 rounded-full transition-all ${
              i < paid ? "bg-emerald-500" : "bg-slate-200 dark:bg-slate-700"
            }`}
          />
          <span className="text-[10px] text-muted-foreground">F{i + 1}</span>
        </div>
      ))}
      <span className="ml-2 text-xs font-medium text-muted-foreground">{paid}/{safeTotal}</span>
    </div>
  );
}

const ClientReferrals = () => {
  const { user } = useClientAuth();
  const qc = useQueryClient();
  const [savingMethod, setSavingMethod] = useState<string | null>(null);

  const { data: canonicalData, refetch } = useCanonicalClientData(user?.id);
  const codeRow = (canonicalData?.referralCodes || [])[0] || null;
  const profile = canonicalData?.profile || null;
  const referrals = canonicalData?.clientReferrals || [];

  useEffect(() => {
    if (!user?.id || codeRow?.code) return;
    portalClient.rpc("ensure_client_referral_code" as any, { p_user_id: user.id }).then(() => {
      qc.invalidateQueries({ queryKey: ["canonical-client-data", user.id] });
      refetch();
    });
  }, [user?.id, codeRow?.code, qc, refetch]);

  const referralCode = codeRow?.code as string | undefined;

  const currentMethod = useMemo(() => {
    const pending = referrals.find(
      (r: any) => r.payment_method && !["reward_issued"].includes(r.reward_status)
    );
    return (pending?.payment_method as string) === "paypal" ? "interac" : ((pending?.payment_method as string) || "interac");
  }, [referrals]);

  const [selectedMethod, setSelectedMethod] = useState<string>(currentMethod);
  useMemo(() => setSelectedMethod(currentMethod), [currentMethod]);

  const stats = {
    total: referrals.length,
    inProgress: referrals.filter((r: any) =>
      ["pending", "code_used", "order_created", "service_activated", "cycle_1_paid", "cycle_2_paid"].includes(r.status)
    ).length,
    qualified: referrals.filter((r: any) =>
      ["qualified", "reward_pending", "reward_issued"].includes(r.status)
    ).length,
    rewardsPending: referrals.filter((r: any) => r.reward_status === "reward_pending").length,
    rewardsIssued: referrals.filter((r: any) => r.reward_status === "reward_issued").length,
    totalEarned: referrals
      .filter((r: any) => r.reward_status === "reward_issued")
      .reduce((sum: number, r: any) => sum + Number(r.reward_amount || 0), 0),
  };

  const referralLink = referralCode
    ? `https://nivra-telecom.ca/commander?ref=${referralCode}`
    : "";

  const copyCode = () => {
    if (referralCode) {
      navigator.clipboard.writeText(referralCode);
      toast.success("Code copié !");
    }
  };

  const copyLink = () => {
    if (referralLink) {
      navigator.clipboard.writeText(referralLink);
      toast.success("Lien copié ✓");
    }
  };

  const shareCode = () => {
    const text = `Utilise mon code ${referralCode} chez Nivra Télécom : tu reçois 5$/mois × 10 mois = 50$ de rabais total, et moi je reçois 25$ 🎁 ${referralLink}`;
    if (navigator.share) {
      navigator.share({ title: "Nivra Parrainage", text }).catch(() => {});
    } else {
      navigator.clipboard.writeText(text);
      toast.success("Message copié !");
    }
  };

  const savePaymentMethod = async (method: string) => {
    if (!user?.id) return;
    setSavingMethod(method);
    try {
      const { error } = await portalClient
        .from("client_referrals" as any)
        .update({ payment_method: method })
        .eq("referrer_user_id", user.id)
        .neq("reward_status", "reward_issued");
      if (error) throw error;
      setSelectedMethod(method);
      toast.success(`Mode de versement mis à jour : ${PAYMENT_LABELS[method]}`);
      qc.invalidateQueries({ queryKey: ["canonical-client-data", user.id] });
    } catch (e: any) {
      toast.error(e?.message || "Erreur lors de la mise à jour");
    } finally {
      setSavingMethod(null);
    }
  };

  const shareText = `Essayez Nivra Telecom ! ${referralLink}`;
  const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(shareText)}`;
  const emailUrl = `mailto:?subject=${encodeURIComponent("Essayez Nivra Telecom")}&body=${encodeURIComponent(shareText)}`;
  const smsUrl = `sms:?body=${encodeURIComponent(shareText)}`;

  return (
    <ClientLayout>
      <div className="max-w-4xl mx-auto space-y-6 p-4 sm:p-6">
        {/* Header */}
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold text-foreground flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-emerald-50 dark:bg-emerald-900/20 flex items-center justify-center">
              <Gift className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
            </div>
            Programme de parrainage
          </h1>
          <p className="text-muted-foreground mt-2 text-sm sm:text-base">
            Parrainez vos proches : après <strong>3 factures mensuelles consécutives payées</strong>, vous recevez
            <strong> 25 $ (versement unique)</strong> et <strong>300 points de fidélité</strong>. Versement Interac e-Transfer (recommandé)
            ou carte-cadeau Visa/Mastercard, effectué dans un délai de 7 à 14 jours.
          </p>
        </div>

        {/* Referral Code Card */}
        <Card className="border-primary/20 overflow-hidden">
          <div className="bg-gradient-to-r from-primary to-primary/80 p-6 sm:p-8">
            <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-5">
              <div>
                <p className="text-primary-foreground/70 text-sm font-medium mb-2">Votre code de parrainage</p>
                <p className="text-3xl sm:text-4xl font-bold font-mono tracking-widest text-primary-foreground">
                  {referralCode || "Génération en cours…"}
                </p>
                {codeRow?.usage_count !== undefined && (
                  <p className="text-primary-foreground/60 text-xs mt-2">
                    Utilisé {codeRow.usage_count} fois
                  </p>
                )}
              </div>
              <div className="flex gap-2">
                <Button
                  onClick={copyCode}
                  variant="outline"
                  className="bg-primary-foreground/10 border-primary-foreground/20 text-primary-foreground hover:bg-primary-foreground/20 gap-2"
                  disabled={!referralCode}
                >
                  <Copy className="w-4 h-4" />
                  Copier
                </Button>
                <Button
                  onClick={shareCode}
                  variant="secondary"
                  className="gap-2"
                  disabled={!referralCode}
                >
                  <Share2 className="w-4 h-4" />
                  Partager
                </Button>
              </div>
            </div>
          </div>
          <CardContent className="p-5 bg-muted/30">
            <div className="flex items-start gap-3">
              <div className="w-8 h-8 rounded-lg bg-emerald-100 dark:bg-emerald-900/20 flex items-center justify-center shrink-0 mt-0.5">
                <CreditCard className="w-4 h-4 text-emerald-600 dark:text-emerald-400" />
              </div>
              <div>
                <p className="font-medium text-sm text-foreground mb-1">Comment ça fonctionne ?</p>
                <ol className="text-sm text-muted-foreground space-y-1 list-decimal list-inside">
                  <li>Partagez votre code de parrainage</li>
                  <li>Votre proche commande chez Nivra Telecom avec votre code</li>
                  <li>Il complète <strong>3 factures mensuelles consécutives</strong> payées</li>
                  <li>Nous validons automatiquement le dossier</li>
                  <li>Vous recevez <strong>25 $</strong> + <strong>300 points de fidélité</strong> (versement 7 à 14 jours)</li>
                </ol>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Payment method preference */}
        <Card>
          <CardContent className="p-5 space-y-4">
            <div>
              <p className="font-medium text-sm text-foreground flex items-center gap-2">
                <Wallet className="w-4 h-4 text-primary" />
                Mode de versement préféré
              </p>
              <p className="text-xs text-muted-foreground mt-1">
                S'applique à vos prochains versements (non rétroactif sur les récompenses déjà émises).
              </p>
            </div>
            <div className="grid sm:grid-cols-3 gap-2">
              {PAYMENT_OPTIONS.map((opt) => {
                const active = selectedMethod === opt.value;
                return (
                  <button
                    key={opt.value}
                    type="button"
                    onClick={() => savePaymentMethod(opt.value)}
                    disabled={savingMethod !== null}
                    className={`text-left p-3 rounded-lg border transition-all ${
                      active
                        ? "border-primary bg-primary/5 ring-2 ring-primary/20"
                        : "border-border hover:border-primary/40 hover:bg-muted/50"
                    } ${savingMethod ? "opacity-60 cursor-wait" : "cursor-pointer"}`}
                  >
                    <p className="text-sm font-medium text-foreground">{opt.label}</p>
                    <p className="text-[11px] text-muted-foreground mt-0.5">{opt.desc}</p>
                    {active && (
                      <Badge className="mt-2 bg-primary/10 text-primary border-0 text-[10px]">
                        Sélectionné
                      </Badge>
                    )}
                  </button>
                );
              })}
            </div>
          </CardContent>
        </Card>

        {/* Share Link */}
        {referralCode && (
          <Card>
            <CardContent className="p-5 space-y-4">
              <div>
                <p className="font-medium text-sm text-foreground mb-1 flex items-center gap-2">
                  <LinkIcon className="w-4 h-4 text-primary" />
                  Partagez votre lien de parrainage
                </p>
                <p className="text-xs text-muted-foreground mb-3">
                  Copiez le lien ou partagez-le directement sur vos réseaux.
                </p>
                <div className="flex flex-col sm:flex-row gap-2">
                  <input
                    type="text"
                    readOnly
                    value={referralLink}
                    className="flex-1 px-3 py-2 text-sm font-mono bg-muted/50 rounded-lg border truncate"
                    onClick={(e) => (e.target as HTMLInputElement).select()}
                  />
                  <Button onClick={copyLink} variant="outline" className="gap-2 shrink-0">
                    <Copy className="w-4 h-4" />
                    Copier le lien
                  </Button>
                </div>
              </div>
              <div className="flex flex-wrap gap-2">
                <Button asChild variant="outline" size="sm" className="gap-2">
                  <a href={whatsappUrl} target="_blank" rel="noopener noreferrer">
                    <MessageCircle className="w-4 h-4 text-emerald-600" /> WhatsApp
                  </a>
                </Button>
                <Button asChild variant="outline" size="sm" className="gap-2">
                  <a href={emailUrl}>
                    <Mail className="w-4 h-4 text-sky-600" /> Email
                  </a>
                </Button>
                <Button asChild variant="outline" size="sm" className="gap-2 sm:hidden">
                  <a href={smsUrl}>
                    <Smartphone className="w-4 h-4 text-amber-600" /> SMS
                  </a>
                </Button>
              </div>
            </CardContent>
          </Card>
        )}

        {/* Live earnings dashboard */}
        <Card>
          <CardContent className="p-5">
            <h3 className="text-base font-semibold text-foreground mb-3 flex items-center gap-2">
              <DollarSign className="w-4 h-4 text-emerald-600" />
              Mes gains de parrainage
            </h3>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 text-center">
              <div className="p-3 rounded-lg bg-emerald-50 dark:bg-emerald-900/20">
                <p className="text-xs text-muted-foreground">Total reçu</p>
                <p className="text-xl font-bold text-emerald-700 dark:text-emerald-300">{stats.totalEarned}$</p>
              </div>
              <div className="p-3 rounded-lg bg-amber-50 dark:bg-amber-900/20">
                <p className="text-xs text-muted-foreground">En attente</p>
                <p className="text-xl font-bold text-amber-700 dark:text-amber-300">{stats.rewardsPending * 25}$</p>
              </div>
              <div className="p-3 rounded-lg bg-sky-50 dark:bg-sky-900/20">
                <p className="text-xs text-muted-foreground">Qualifiés</p>
                <p className="text-xl font-bold text-sky-700 dark:text-sky-300">{stats.qualified}</p>
              </div>
              <div className="p-3 rounded-lg bg-muted/40">
                <p className="text-xs text-muted-foreground">En cours</p>
                <p className="text-xl font-bold text-foreground">{stats.inProgress}</p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Stats Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4">
          {[
            { icon: Users, label: "Parrainages", value: stats.total, color: "text-sky-500", bg: "bg-sky-50 dark:bg-sky-900/20" },
            { icon: Clock, label: "En cours", value: stats.inProgress, color: "text-amber-500", bg: "bg-amber-50 dark:bg-amber-900/20" },
            { icon: CheckCircle, label: "Qualifiés", value: stats.qualified, color: "text-emerald-500", bg: "bg-emerald-50 dark:bg-emerald-900/20" },
            { icon: DollarSign, label: "Reçu", value: `${stats.totalEarned}$`, color: "text-emerald-600", bg: "bg-emerald-50 dark:bg-emerald-900/20" },
          ].map(({ icon: Icon, label, value, color, bg }) => (
            <Card key={label} className="overflow-hidden">
              <CardContent className="p-4">
                <div className="flex items-center gap-2 mb-2">
                  <div className={`w-8 h-8 rounded-lg ${bg} flex items-center justify-center`}>
                    <Icon className={`w-4 h-4 ${color}`} />
                  </div>
                </div>
                <p className="text-2xl font-bold text-foreground">{value}</p>
                <p className="text-xs text-muted-foreground mt-0.5">{label}</p>
              </CardContent>
            </Card>
          ))}
        </div>

        {stats.rewardsPending > 0 && (
          <div className="flex items-center gap-3 p-4 rounded-xl bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 text-amber-800 dark:text-amber-300">
            <Gift className="w-5 h-5 shrink-0" />
            <p className="text-sm font-medium">
              {stats.rewardsPending} récompense{stats.rewardsPending > 1 ? "s" : ""} en attente d'émission — Votre versement arrive bientôt !
            </p>
          </div>
        )}

        {/* History */}
        <div>
          <h2 className="text-lg font-semibold text-foreground mb-4 flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-muted-foreground" />
            Historique de parrainage
          </h2>

          {referrals.length === 0 ? (
            <Card>
              <CardContent className="py-16 text-center">
                <div className="w-16 h-16 rounded-2xl bg-muted flex items-center justify-center mx-auto mb-4">
                  <Gift className="w-8 h-8 text-muted-foreground" />
                </div>
                <p className="font-medium text-foreground mb-1">Aucun parrainage pour le moment</p>
                <p className="text-sm text-muted-foreground mb-4">
                  Partagez votre code pour commencer à gagner des récompenses
                </p>
                <Button onClick={shareCode} className="gap-2" disabled={!referralCode}>
                  <Share2 className="w-4 h-4" />
                  Partager mon code
                </Button>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-3">
              {referrals.map((r: any) => (
                <Card key={r.id} className="overflow-hidden">
                  <CardContent className="p-4 sm:p-5">
                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                      <div className="space-y-3 flex-1">
                        <div className="flex items-center gap-2 flex-wrap">
                          <Badge className={`${getStatusColor(r.status)} border-0 text-xs`}>
                            {STATUS_LABELS[r.status] || r.status}
                          </Badge>
                          {r.payment_method && (
                            <Badge variant="outline" className="text-xs">
                              {PAYMENT_LABELS[r.payment_method] || r.payment_method}
                            </Badge>
                          )}
                          {r.reward_status === "reward_issued" && (
                            <Badge className="bg-emerald-100 text-emerald-700 border-0 text-xs">
                              🎁 {r.reward_amount}$ reçu
                            </Badge>
                          )}
                          {r.reward_status === "reward_pending" && (
                            <Badge className="bg-amber-100 text-amber-700 border-0 text-xs">
                              ⏳ En attente
                            </Badge>
                          )}
                        </div>

                        <CycleProgress
                          paid={r.qualifying_cycles_paid || 0}
                          total={r.required_cycles || 3}
                        />


                        <p className="text-xs text-muted-foreground">
                          Parrainé le {new Date(r.created_at).toLocaleDateString("fr-CA")}
                        </p>
                      </div>

                      <div className="text-right shrink-0 sm:pl-4">
                        <div className={`inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg ${
                          r.reward_status === "reward_issued"
                            ? "bg-emerald-50 text-emerald-700 dark:bg-emerald-900/20 dark:text-emerald-300"
                            : "bg-muted text-muted-foreground"
                        }`}>
                          <CreditCard className="w-3.5 h-3.5" />
                          <span className="text-sm font-semibold">{r.reward_amount || 25}$</span>
                        </div>
                        <p className="text-[10px] text-muted-foreground mt-1">Total récompense</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </div>

        {/* Learn more */}
        <div className="text-center pt-2">
          <Link to="/parrainage" className="text-sm text-primary hover:underline inline-flex items-center gap-1">
            En savoir plus sur le programme
            <ArrowRight className="w-3.5 h-3.5" />
          </Link>
        </div>

        {/* Terms */}
        <div className="text-xs text-muted-foreground space-y-1 p-4 bg-muted/40 rounded-xl border">
          <p className="font-medium text-foreground">Conditions du programme</p>
          <ul className="list-disc list-inside space-y-0.5">
            <li>Récompense parrain : 25$ versement unique • Rabais filleul : 5$/mois × 10 mois = 50$ de rabais total</li>
            <li>Le client référé doit compléter <strong>2 cycles mensuels payés</strong> pour qualifier</li>
            <li>Versements au choix : Interac e-Transfer ou carte-cadeau Visa/Mastercard</li>
            <li>L'auto-parrainage est interdit</li>
            <li>Un seul parrainage par nouveau client</li>
            <li>Nivra se réserve le droit de disqualifier les parrainages frauduleux</li>
          </ul>
        </div>
      </div>
    </ClientLayout>
  );
};

export default ClientReferrals;
